name: dio_cache_interceptor
description: Dio HTTP cache interceptor with multiple stores respecting HTTP directives (ETag, Last-Modified, Cache-Control) with options.
repository: https://github.com/llfbandit/dio_cache_interceptor
issue_tracker: https://github.com/llfbandit/dio_cache_interceptor/issues

version: 1.0.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio:
    git:
      url: git://github.com/TitanKing/dio.git
      path: dio
      ref: null-safety
  sqflite: 2.0.0-nullsafety.2
  uuid: 3.0.0-nullsafety.1
  meta: ^1.2.4
  path: ^1.7.0

dependency_overrides:
  path_provider_platform_interface: 2.0.0-nullsafety

dev_dependencies:
  pedantic: ^1.9.0
  # Tests are done in example project
