name: dio_cache_interceptor
description: Dio HTTP cache interceptor with multiple stores respecting HTTP directives (ETag, Last-Modified, Cache-Control) with options.
repository: https://github.com/llfbandit/dio_cache_interceptor
issue_tracker: https://github.com/llfbandit/dio_cache_interceptor/issues

version: 2.0.0-beta.2

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  dio: ^3.0.10
  meta: ^1.2.4
  moor: ^3.4.0
  path: ^1.7.0
  path_provider: 2.0.0-nullsafety.1
  sqlite3_flutter_libs: ^0.4.0+1

dependency_overrides:
  sqlite3: 0.1.10-nullsafety.0
  ffi: ^1.0.0

dev_dependencies:
  moor_generator: ^3.4.1
  build_runner:
  pedantic: ^1.9.0
  # Tests are done in example project
